-- =============================================================
-- V1: Initial Schema
-- Flyway runs this ONCE and records it in flyway_schema_history.
-- If you change your entity, you do NOT edit this file —
-- instead you create V2__, V3__ etc. That's the whole point.
-- =============================================================

-- Users table (admin, tech panel, HR panel login accounts)
CREATE TABLE IF NOT EXISTS users (
    user_id       VARCHAR(50)  NOT NULL,
    password      VARCHAR(255) NOT NULL,
    user_type     VARCHAR(20)  NOT NULL,   -- ADMIN | TECH_PANEL | HR_PANEL
    login_status  BOOLEAN      DEFAULT FALSE,
    enabled       BOOLEAN      DEFAULT TRUE,
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP,

    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT chk_user_type CHECK (user_type IN ('ADMIN', 'TECH_PANEL', 'HR_PANEL'))
);

-- Candidates table (professional details)
CREATE TABLE IF NOT EXISTS candidates (
    candidate_id    VARCHAR(50)  NOT NULL,
    primary_skills  VARCHAR(200),
    secondary_skills VARCHAR(200),
    experience      FLOAT,
    qualification   VARCHAR(100),
    designation     VARCHAR(100),
    notice_period   INTEGER,
    location        VARCHAR(100),
    share_details   BOOLEAN      DEFAULT FALSE,
    created_at      TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP,

    CONSTRAINT pk_candidates PRIMARY KEY (candidate_id)
);

-- Profiles table (personal details — 1-to-1 with candidates)
-- Uses same PK as candidates (shared primary key pattern)
CREATE TABLE IF NOT EXISTS profiles (
    candidate_id  VARCHAR(50)  NOT NULL,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    gender        VARCHAR(20),
    street        VARCHAR(200),
    location      VARCHAR(100),
    city          VARCHAR(100),
    state         VARCHAR(100),
    pincode       VARCHAR(20),
    mobile_no     VARCHAR(20),
    email_id      VARCHAR(100) UNIQUE,
    password      VARCHAR(255),
    created_at    TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP,

    CONSTRAINT pk_profiles     PRIMARY KEY (candidate_id),
    CONSTRAINT fk_profile_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidates(candidate_id)
        ON DELETE CASCADE   -- deleting a candidate removes their profile too
);

-- Interview schedules table
CREATE TABLE IF NOT EXISTS interview_schedules (
    interview_id            VARCHAR(50) NOT NULL,
    candidate_id            VARCHAR(50) NOT NULL,
    subject                 VARCHAR(100),
    tech_id                 VARCHAR(50),
    interview_date          DATE,
    interview_time          TIME,
    tech_rating             FLOAT,
    emp_hr_id               VARCHAR(50),
    emp_hr_interview_date   DATE,
    emp_hr_interview_time   TIME,
    emp_hr_rating           FLOAT,
    result                  VARCHAR(50),
    share_result            BOOLEAN     DEFAULT FALSE,
    created_at              TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP,

    CONSTRAINT pk_interview_schedules PRIMARY KEY (interview_id),
    CONSTRAINT fk_interview_candidate
        FOREIGN KEY (candidate_id) REFERENCES candidates(candidate_id)
);
